create type public.record_status as enum('active','inactive');
create type public.goal_status as enum('active','completed','paused');
create type public.session_status as enum('planned','completed','canceled');

create table public.students(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,linked_user_id uuid references auth.users(id) on delete set null,first_name text not null,last_name text not null,preferred_name text,email text,pronouns text,status public.record_status not null default 'active',general_context text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,linked_user_id));
create table public.cohorts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,description text,status public.record_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.cohort_members(cohort_id uuid not null references public.cohorts(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,joined_at timestamptz not null default now(),primary key(cohort_id,student_id));
create table public.focus_areas(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,description text,active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,name));
create table public.student_goals(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,focus_area_id uuid references public.focus_areas(id) on delete set null,title text not null,description text,status public.goal_status not null default 'active',target_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),completed_at timestamptz);
create table public.sessions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,coach_user_id uuid not null references auth.users(id),student_id uuid references public.students(id) on delete cascade,cohort_id uuid references public.cohorts(id) on delete cascade,title text not null,session_date date not null,start_time time,duration_minutes integer check(duration_minutes between 1 and 1440),status public.session_status not null default 'planned',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check((student_id is null)<>(cohort_id is null)));
create table public.session_focus_areas(session_id uuid not null references public.sessions(id) on delete cascade,focus_area_id uuid not null references public.focus_areas(id) on delete cascade,primary key(session_id,focus_area_id));
create table public.session_private_notes(id uuid primary key default gen_random_uuid(),session_id uuid not null unique references public.sessions(id) on delete cascade,organization_id uuid not null references public.organizations(id) on delete cascade,author_user_id uuid not null references auth.users(id),content text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.session_recaps(id uuid primary key default gen_random_uuid(),session_id uuid not null unique references public.sessions(id) on delete cascade,organization_id uuid not null references public.organizations(id) on delete cascade,student_id uuid references public.students(id) on delete cascade,title text,content text not null default '',published_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create index students_org_idx on public.students(organization_id);create index goals_student_idx on public.student_goals(student_id,status);create index sessions_org_date_idx on public.sessions(organization_id,session_date desc);create index recaps_session_idx on public.session_recaps(session_id);
create function public.touch_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end$$;
create trigger students_touch before update on public.students for each row execute function public.touch_updated_at();create trigger cohorts_touch before update on public.cohorts for each row execute function public.touch_updated_at();create trigger focus_touch before update on public.focus_areas for each row execute function public.touch_updated_at();create trigger goals_touch before update on public.student_goals for each row execute function public.touch_updated_at();create trigger sessions_touch before update on public.sessions for each row execute function public.touch_updated_at();create trigger notes_touch before update on public.session_private_notes for each row execute function public.touch_updated_at();create trigger recaps_touch before update on public.session_recaps for each row execute function public.touch_updated_at();

create function public.is_organization_coach(org uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.organization_memberships where organization_id=org and user_id=auth.uid() and role in('owner','coach'))$$;
create function public.is_own_student(student uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.students where id=student and linked_user_id=auth.uid())$$;
create function public.is_own_cohort(cohort uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.cohort_members cm join public.students s on s.id=cm.student_id where cm.cohort_id=cohort and s.linked_user_id=auth.uid())$$;
create function public.can_view_session(target uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.sessions s where s.id=target and(public.is_organization_coach(s.organization_id) or public.is_own_student(s.student_id) or public.is_own_cohort(s.cohort_id)))$$;

alter table public.students enable row level security;alter table public.cohorts enable row level security;alter table public.cohort_members enable row level security;alter table public.focus_areas enable row level security;alter table public.student_goals enable row level security;alter table public.sessions enable row level security;alter table public.session_focus_areas enable row level security;alter table public.session_private_notes enable row level security;alter table public.session_recaps enable row level security;
create policy students_read on public.students for select to authenticated using(public.is_organization_coach(organization_id) or linked_user_id=auth.uid());create policy students_write on public.students for all to authenticated using(public.is_organization_coach(organization_id)) with check(public.is_organization_coach(organization_id));
create policy cohorts_read on public.cohorts for select to authenticated using(public.is_organization_coach(organization_id) or public.is_own_cohort(id));create policy cohorts_write on public.cohorts for all to authenticated using(public.is_organization_coach(organization_id)) with check(public.is_organization_coach(organization_id));
create policy cohort_members_read on public.cohort_members for select to authenticated using(public.is_organization_coach((select organization_id from public.cohorts where id=cohort_id)) or public.is_own_student(student_id));create policy cohort_members_write on public.cohort_members for all to authenticated using(public.is_organization_coach((select organization_id from public.cohorts where id=cohort_id))) with check(public.is_organization_coach((select organization_id from public.cohorts where id=cohort_id)));
create policy focus_read on public.focus_areas for select to authenticated using(public.is_organization_member(organization_id));create policy focus_write on public.focus_areas for all to authenticated using(public.is_organization_coach(organization_id)) with check(public.is_organization_coach(organization_id));
create policy goals_read on public.student_goals for select to authenticated using(public.is_organization_coach(organization_id) or public.is_own_student(student_id));create policy goals_write on public.student_goals for all to authenticated using(public.is_organization_coach(organization_id)) with check(public.is_organization_coach(organization_id));
create policy sessions_read on public.sessions for select to authenticated using(public.is_organization_coach(organization_id) or public.is_own_student(student_id) or public.is_own_cohort(cohort_id));create policy sessions_write on public.sessions for all to authenticated using(public.is_organization_coach(organization_id)) with check(public.is_organization_coach(organization_id) and coach_user_id=auth.uid());
create policy session_focus_read on public.session_focus_areas for select to authenticated using(public.can_view_session(session_id));create policy session_focus_write on public.session_focus_areas for all to authenticated using(public.is_organization_coach((select organization_id from public.sessions where id=session_id))) with check(public.is_organization_coach((select organization_id from public.sessions where id=session_id)));
create policy private_notes_coach_only on public.session_private_notes for all to authenticated using(public.is_organization_coach(organization_id)) with check(public.is_organization_coach(organization_id) and author_user_id=auth.uid());
create policy recaps_coach on public.session_recaps for all to authenticated using(public.is_organization_coach(organization_id)) with check(public.is_organization_coach(organization_id));create policy recaps_student_read on public.session_recaps for select to authenticated using(published_at is not null and((student_id is not null and public.is_own_student(student_id))or(student_id is null and public.can_view_session(session_id))));
